{"name": "Login with invalid credentials (Should FAIL)", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'dashboard' in 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login'\n +  where 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login' = <built-in method lower of str object at 0x00000187A0616AA0>()\n +    where <built-in method lower of str object at 0x00000187A0616AA0> = 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login'.lower\n +      where 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login' = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"8053537864ed0a5a93d4a41ab192fb31\")>.current_url\n +        where <selenium.webdriver.chrome.webdriver.WebDriver (session=\"8053537864ed0a5a93d4a41ab192fb31\")> = <tests.test_login.TestLogin object at 0x00000187A05D2FD0>.driver", "trace": "self = <tests.test_login.TestLogin object at 0x00000187A05D2FD0>\n\n    @allure.title(\"Login with invalid credentials (Should FAIL)\")\n    def test_login_invalid(self):\n        login_page = LoginPage(self.driver)\n        login_page.login(\"invalidUser\", \"wrongPass\")\n        # Cố tình kiểm tra sai để FAIL\n>       assert \"dashboard\" in self.driver.current_url.lower()\nE       assert 'dashboard' in 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login'\nE        +  where 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login' = <built-in method lower of str object at 0x00000187A0616AA0>()\nE        +    where <built-in method lower of str object at 0x00000187A0616AA0> = 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login'.lower\nE        +      where 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login' = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"8053537864ed0a5a93d4a41ab192fb31\")>.current_url\nE        +        where <selenium.webdriver.chrome.webdriver.WebDriver (session=\"8053537864ed0a5a93d4a41ab192fb31\")> = <tests.test_login.TestLogin object at 0x00000187A05D2FD0>.driver\n\ntests\\test_login.py:20: AssertionError"}, "start": 1752586287955, "stop": 1752586300414, "uuid": "97323d94-e3f1-4610-973d-2ed997ff9f9e", "historyId": "5da0defd295c5b73991b1ce5dbbe7dd0", "testCaseId": "5da0defd295c5b73991b1ce5dbbe7dd0", "fullName": "tests.test_login.TestLogin#test_login_invalid", "labels": [{"name": "epic", "value": "Login Module"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "AnhHuy"}, {"name": "thread", "value": "25996-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}