{"name": "Login with invalid credentials (Should FAIL)", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'dashboard' in 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login'\n +  where 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login' = <built-in method lower of str object at 0x00000238B285D920>()\n +    where <built-in method lower of str object at 0x00000238B285D920> = 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login'.lower\n +      where 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login' = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"4ee32302196ae476706130b8d8a11808\")>.current_url\n +        where <selenium.webdriver.chrome.webdriver.WebDriver (session=\"4ee32302196ae476706130b8d8a11808\")> = <tests.test_login.TestLogin object at 0x00000238B279E490>.driver", "trace": "self = <tests.test_login.TestLogin object at 0x00000238B279E490>\n\n    @allure.title(\"Login with invalid credentials (Should FAIL)\")\n    def test_login_invalid(self):\n        login_page = LoginPage(self.driver)\n        login_page.login(\"invalidUser\", \"wrongPass\")\n>       assert \"dashboard\" in self.driver.current_url.lower()\nE       assert 'dashboard' in 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login'\nE        +  where 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login' = <built-in method lower of str object at 0x00000238B285D920>()\nE        +    where <built-in method lower of str object at 0x00000238B285D920> = 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login'.lower\nE        +      where 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login' = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"4ee32302196ae476706130b8d8a11808\")>.current_url\nE        +        where <selenium.webdriver.chrome.webdriver.WebDriver (session=\"4ee32302196ae476706130b8d8a11808\")> = <tests.test_login.TestLogin object at 0x00000238B279E490>.driver\n\ntests\\test_login.py:21: AssertionError"}, "start": 1752587261951, "stop": 1752587274604, "uuid": "40499e12-fc19-4b0a-8151-ef3ec6182328", "historyId": "5da0defd295c5b73991b1ce5dbbe7dd0", "testCaseId": "5da0defd295c5b73991b1ce5dbbe7dd0", "fullName": "tests.test_login.TestLogin#test_login_invalid", "labels": [{"name": "epic", "value": "Login Module"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "AnhHuy"}, {"name": "thread", "value": "8672-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}