{"name": "Login with invalid credentials (Should FAIL)", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'dashboard' in 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login'\n +  where 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login' = <built-in method lower of str object at 0x000002AD7A876AA0>()\n +    where <built-in method lower of str object at 0x000002AD7A876AA0> = 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login'.lower\n +      where 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login' = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"42a6c9a1a2f6eb8ce9c5d2bb41f1551c\")>.current_url\n +        where <selenium.webdriver.chrome.webdriver.WebDriver (session=\"42a6c9a1a2f6eb8ce9c5d2bb41f1551c\")> = <tests.test_login.TestLogin object at 0x000002AD7A832FD0>.driver", "trace": "self = <tests.test_login.TestLogin object at 0x000002AD7A832FD0>\n\n    @allure.title(\"Login with invalid credentials (Should FAIL)\")\n    def test_login_invalid(self):\n        login_page = LoginPage(self.driver)\n        login_page.login(\"invalidUser\", \"wrongPass\")\n>       assert \"dashboard\" in self.driver.current_url.lower()\nE       assert 'dashboard' in 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login'\nE        +  where 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login' = <built-in method lower of str object at 0x000002AD7A876AA0>()\nE        +    where <built-in method lower of str object at 0x000002AD7A876AA0> = 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login'.lower\nE        +      where 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login' = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"42a6c9a1a2f6eb8ce9c5d2bb41f1551c\")>.current_url\nE        +        where <selenium.webdriver.chrome.webdriver.WebDriver (session=\"42a6c9a1a2f6eb8ce9c5d2bb41f1551c\")> = <tests.test_login.TestLogin object at 0x000002AD7A832FD0>.driver\n\ntests\\test_login.py:21: AssertionError"}, "start": 1752586589211, "stop": 1752586602822, "uuid": "e1e1703e-03c9-4bb5-97ad-ff9187fcfd12", "historyId": "5da0defd295c5b73991b1ce5dbbe7dd0", "testCaseId": "5da0defd295c5b73991b1ce5dbbe7dd0", "fullName": "tests.test_login.TestLogin#test_login_invalid", "labels": [{"name": "epic", "value": "Login Module"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "AnhHuy"}, {"name": "thread", "value": "11912-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}