{"name": "Login with invalid credentials (Should FAIL)", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'dashboard' in 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login'\n +  where 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login' = <built-in method lower of str object at 0x000001588C7FF050>()\n +    where <built-in method lower of str object at 0x000001588C7FF050> = 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login'.lower\n +      where 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login' = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"a39c4a327398c2a5f7402abbd84f220d\")>.current_url\n +        where <selenium.webdriver.chrome.webdriver.WebDriver (session=\"a39c4a327398c2a5f7402abbd84f220d\")> = <tests.test_login.TestLogin object at 0x000001588C3CE490>.driver", "trace": "self = <tests.test_login.TestLogin object at 0x000001588C3CE490>\n\n    @allure.title(\"Login with invalid credentials (Should FAIL)\")\n    def test_login_invalid(self):\n        login_page = LoginPage(self.driver)\n        login_page.login(\"invalidUser\", \"wrongPass\")\n>       assert \"dashboard\" in self.driver.current_url.lower()\nE       assert 'dashboard' in 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login'\nE        +  where 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login' = <built-in method lower of str object at 0x000001588C7FF050>()\nE        +    where <built-in method lower of str object at 0x000001588C7FF050> = 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login'.lower\nE        +      where 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login' = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"a39c4a327398c2a5f7402abbd84f220d\")>.current_url\nE        +        where <selenium.webdriver.chrome.webdriver.WebDriver (session=\"a39c4a327398c2a5f7402abbd84f220d\")> = <tests.test_login.TestLogin object at 0x000001588C3CE490>.driver\n\ntests\\test_login.py:21: AssertionError"}, "start": 1752588735597, "stop": 1752588747641, "uuid": "bab5fca8-face-4fdd-a3ac-cec1385c6622", "historyId": "5da0defd295c5b73991b1ce5dbbe7dd0", "testCaseId": "5da0defd295c5b73991b1ce5dbbe7dd0", "fullName": "tests.test_login.TestLogin#test_login_invalid", "labels": [{"name": "epic", "value": "Login Module"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "AnhHuy"}, {"name": "thread", "value": "1852-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}